### ISSUE TITLE
NFS scripts fail to detect unrestricted NFS shares

### ISSUE THREAD

**Issue by cnotin** [nmap/nmap#1469]
I've scanned a server with unrestricted NFS shares exposed.
The following nmap command fails to detect the shares:
`nmap -p 111 --open --script=nfs-showmount,nfs-ls <ip>`

Contrary to `showmount -e <ip>` which correctly lists the shares.

I've captured the network trafic in both cases.
The sequence I see is:
* nmap:
1. RPC V2 DUMP call to TCP/111
2. Server doesn't answer
3. Nmap retry a second time

* showmount:
1. RPC V4 GETADDR call for program "MOUNT" to TCP/111
2. Server answers
3. Same with V3
4. RPC V2 GETPORTAL call for program "MOUNT"
5. Server answers with the port
6. RPC V3 EXPORT call for program "MOUNT" to the port obtained just before

I don't have a code contribution yet but I wanted to raise this issue which can create false negatives.

**Comment by dmiller-nmap** [comment]
RPCBIND (program 100000) version 3 and 4 is quite different than PORTMAP (program 100000 also) version 2, and we only have PORTMAP implemented. I'm working on implementing RPCBIND so we'll be able to get the correct ports. A better implementation may also use GETPORT instead of DUMP, but we'll see how that goes. Thanks for reporting!

**Comment by dmiller-nmap** [comment]
The reason we use DUMP is so that we can just grab all the info once and then use the cached info for all scripts that may need it. We ought to have a fallback using GETPORT, but I'd like to see if the change that I just pushed to SVN will work for you. I haven't heard of the DUMP function not being supported or being restricted before.

**Comment by cnotin** [comment]
Thank you @dmiller-nmap, I will check, and let you know how it works with your change!

**Comment by cnotin** [comment]
Thanks again but unfortunately it doesn't work better.
I allowed myself to send you an email with more detailed information.

**Comment by Stefan-mcp** [comment]
This is reproducible with kali and metaspoiltable 2. This seem more like a regression rather than a new support being required - the metaspoilable vm hasn't changed in years and nmaps scripts working against it in previous versions can be see documented all over the net in various tutorials. See here for V7.4 example working correctly (https://spreadsecurity.github.io/2017/02/19/reconnaissance-with-nmap-scripting-engine.html)

**Comment by Stefan-mcp** [comment]
I've tested further by downloading the old 7.4 version against the same target, the scripts work correctly when that version is used, including the nfs-ls.
I perform the test using nmap7.8 on kali vm, and nmap7.4 on windows 10  - both against the metasploitable2 vm

**Comment by Stefan-mcp** [comment]
confirmed with both versions installed on same os now..

root@kali:~/# nmap -sS -sV -p 111,2049 --script *nfs* 10.0.2.5
Starting Nmap 7.80 ( https://nmap.org ) at 2020-02-19 16:52 GMT
Nmap scan report for 10.0.2.5
Host is up (0.00039s latency).

PORT     STATE SERVICE VERSION
111/tcp  open  rpcbind 2 (RPC #100000)
2049/tcp open  nfs     2-4 (RPC #100003)
MAC Address: 08:00:27:A9:C5:6B (Oracle VirtualBox virtual NIC)

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 19.81 seconds
--
root@kali:~/Desktop/nmap-7.40# ./nmap -sS -sV -p 111,2049 --script *nfs* 10.0.2.5

Starting Nmap 7.40 ( https://nmap.org ) at 2020-02-19 16:52 GMT
Nmap scan report for 10.0.2.5
Host is up (0.00036s latency).
PORT     STATE SERVICE VERSION
111/tcp  open  rpcbind 2 (RPC #100000)
| nfs-ls: Volume /
|   access: Read Lookup Modify Extend Delete NoExecute
| PERMISSION  UID  GID  SIZE   TIME                 FILENAME
| drwxr-xr-x  0    0    4096   2012-05-14T03:35:33  bin
| drwxr-xr-x  0    0    4096   2010-04-16T06:16:02  home
| drwxr-xr-x  0    0    4096   2010-03-16T22:57:40  initrd
| lrwxrwxrwx  0    0    32     2010-04-28T20:26:18  initrd.img
| drwxr-xr-x  0    0    4096   2012-05-14T03:35:22  lib
| drwx------  0    0    16384  2010-03-16T22:55:15  lost+found
| drwxr-xr-x  0    0    4096   2010-03-16T22:55:52  media
| drwxr-xr-x  0    0    4096   2010-04-28T20:16:56  mnt
| drwxr-xr-x  0    0    4096   2012-05-14T01:54:53  sbin
| drwxr-xr-x  0    0    4096   2010-04-28T04:06:37  usr
|_
| nfs-showmount: 
|_  / *
| rpcinfo: 
|   program version   port/proto  service
|   100000  2            111/tcp  rpcbind
|   100000  2            111/udp  rpcbind
|   100003  2,3,4       2049/tcp  nfs
|   100003  2,3,4       2049/udp  nfs
|   100005  1,2,3      37739/udp  mountd
|   100005  1,2,3      59227/tcp  mountd
|   100021  1,3,4      37857/tcp  nlockmgr
|   100021  1,3,4      52184/udp  nlockmgr
|   100024  1          56924/udp  status
|_  100024  1          60465/tcp  status
2049/tcp open  nfs     2-4 (RPC #100003)
MAC Address: 08:00:27:A9:C5:6B (Oracle VirtualBox virtual NIC)

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 20.06 seconds
root@kali:~/Desktop/nmap-7.40#

**Comment by nnposter** [comment]
@Stefan-mcp The latest up-to-date Kali is still missing the patches for #1853. I have tested Metasploitable2 with Nmap from SVN and it is working correctly:
```
root@lounge:~# nmap -n -Pn -sT -p111 --script nfs-ls 192.168.48.129
Starting Nmap 7.80SVN ( https://nmap.org ) at 2020-02-28 00:16 MST
Nmap scan report for 192.168.48.129
Host is up (0.00058s latency).

PORT    STATE SERVICE
111/tcp open  rpcbind
| nfs-ls: Volume /
|   access: Read Lookup Modify Extend Delete NoExecute
| PERMISSION  UID  GID  SIZE   TIME                 FILENAME
| drwxr-xr-x  0    0    4096   2012-05-14T03:35:33  bin
| drwxr-xr-x  0    0    4096   2010-04-16T06:16:02  home
| drwxr-xr-x  0    0    4096   2010-03-16T22:57:40  initrd
| lrwxrwxrwx  0    0    32     2010-04-28T20:26:18  initrd.img
| drwxr-xr-x  0    0    4096   2012-05-14T03:35:22  lib
| drwx------  0    0    16384  2010-03-16T22:55:15  lost+found
| drwxr-xr-x  0    0    4096   2010-03-16T22:55:52  media
| drwxr-xr-x  0    0    4096   2010-04-28T20:16:56  mnt
| drwxr-xr-x  0    0    4096   2012-05-14T01:54:53  sbin
| drwxr-xr-x  0    0    4096   2010-04-28T04:06:37  usr
|_

Nmap done: 1 IP address (1 host up) scanned in 0.26 seconds
```
If you do not want to wait for Kali updates, you can refresh `nselib/rpc.lua` on your own from the SVN or GitHub.

**Comment by Stefan-mcp** [comment]
Thanks nnposter,
I built from source as I'd had problems with the smb scripts too - everything is much more stable in the svn version! The 7.8 on kali seg faults randomly when running some of the -sC scripts, shame they haven't merged the updates as this seems resolved entirely in the current svn version.
Thanks again :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nnposter** [comment]
There was also another issue that could cause *intermittent* `mountd` errors on the target. A fix has been committed as r37911 (80f4733c32c4ef9345db7a7cd6bfdcd11df1c5ed).

**Comment by Stefan-mcp** [comment]
Ah, thanks for the heads up, and for your prompt fix 😊 I’ll take a new copy from git.
And #1939 looks like a good catch, I imagine that’s been lurking behind quite a few silent failures or missed positives, great job!

Stef

________________________________

**Comment by nnposter** [comment]
Is this still an issue or did it get resolved with some of the updates up to this point?

**Comment by cnotin** [comment]
Thanks @nnposter 
In my case I still have some servers where Nmap nfs-showmount fails whereas `showmount -e` works fine. The difference with my initial observations above is that now I see RPC V4, V3 and V2 DUMP calls but my servers don't answer to any of them.

**Comment by dmiller-nmap** [comment]
@cnotin If this is still a problem, please reopen this issue and provide output from nmap with the `--script-trace` and `-d4` options, as well as pcaps or dumps of traffic from `showmount -e`. If you are concerned with posting this information publicly, you can send it to dmiller@nmap.com instead.

**Comment by cnotin** [comment]
Thanks for the follow up but it was a very long time ago and I don’t have access anymore to this environment.
