### ISSUE TITLE
NCAP 0.99-r7 failed to setup on Windows10 family edition

### ISSUE THREAD

**Issue by Martinily** [nmap/nmap#1527]
Hello,
I have some trouble installing npcap on my windows 10.
Unknown error 0x8007007e
[install.log](https://github.com/nmap/nmap/files/2999262/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/2999263/NPFInstall.log)
![TIM图片20190323191919](https://user-images.githubusercontent.com/26357319/54865434-9451b680-4da0-11e9-9d54-2fba6b274549.png)

Please give me some help.
Thank you!

**Comment by fyodor** [comment]
Hi @Martinily.  Can you try with Npcap Version 0.991 and let us know what happens?  We have fixed many issues since 0.99-r7.  Thanks!

**Comment by Martinily** [comment]
![TIM图片20190324094955](https://user-images.githubusercontent.com/26357319/54873845-4d080c00-4e1a-11e9-8a83-bac7d3cbb783.jpg)
![TIM图片20190324094959](https://user-images.githubusercontent.com/26357319/54873846-4e393900-4e1a-11e9-80d6-0358e1269b72.png)
![TIM图片20190324095022](https://user-images.githubusercontent.com/26357319/54873847-5002fc80-4e1a-11e9-8162-1bd2fc4f89bd.png)
The same problem still exists.

I can't even uninstall it.
