### ISSUE TITLE
Option -A breaks scan for opened 53/tcp port

### ISSUE THREAD

**Issue by overheavenlyshadows** [nmap/nmap#2821]
**Describe the bug**
When using option -A to scan opened 53/tcp port it goes to "Unexpected error in NSE_TYPE_READ callback.  Error code: 50 (Network is down)"

**To Reproduce**
Scan any host with opened 53 port using macos sonoma 14.3.1 (arm) 

**Expected behavior**
Scanned port.

**Version info (please complete the following information):**
Nmap version 7.94 ( https://nmap.org )
Platform: arm-apple-darwin23.2.0
Compiled with: liblua-5.4.6 openssl-3.2.1 libssh2-1.11.0 libz-1.2.12 libpcre2-10.43 nmap-libpcap-1.10.4 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select

**Additional context**
Initiating Connect Scan at 18:31
Scanning <target_host> (<target_ip>) [1 port]
Discovered open port 53/tcp on <target_ip>
Completed Connect Scan at 18:31, 0.00s elapsed (1 total ports)
Initiating Service scan at 18:31
Scanning 1 service on <target_host> (<target_ip>)
Unexpected error in NSE_TYPE_READ callback.  Error code: 50 (Network is down)
QUITTING!

**Comment by fyodor** [comment]
Thanks for the report.  It looks like we need to handle ENETDOWN error code.  @dmiller-nmap is working on it.

**Comment by overheavenlyshadows** [comment]
@fyodor seems like it was fixed in 7.95

**Comment by overheavenlyshadows** [comment]
Broken again

**Comment by fyodor** [comment]
Thanks for the update @overheavenlyshadows.  We haven't put in the code fix yet but you may not be receiving the "network is down" callback error for other reasons.  We're still working on the permanent fix and hope to have it in the next Nmap release.

**Comment by fyodor** [comment]
Also we discussed it in a meeting today and @dmiller-nmap noted that we should probably also adjust that function (servicescan_read_handler in service_scan.cc) to not quit on unexpected errors there

**Comment by dmiller-nmap** [comment]
Should be fixed in be9c6d96ee3285d7dcbced539282c8a8132dcea7. Let us know if you continue to have problems.

**Comment by manish199014** [comment]
Hello, 

I am trying to run NMAP on my Macboon M2 chip, and getting the same error message. 

```
Starting Nmap 7.95 ( https://nmap.org ) at 2024-06-12 16:48 BST
Unexpected error in NSE_TYPE_READ callback.  Error code: 50 (Network is down)
QUITTING!
```

I tried installing and uninstalling, but the result is always same. 

is there a way, I can fix this? 

Thanks

**Comment by evan-annix** [comment]
Experiencing the same issue here on an M1 Max MacBook on MacOS Sonoma (14.5) with nmap 7.95 installed through Homebrew.

The command string I'm using is:
`nmap -sV -T4 -O -F --version-light 192.168.0.1-254`

Which outputs:
`TCP/IP fingerprinting (for OS scan) requires root privileges.
QUITTING!`

Running the same string with _sudo_ outputs:
`Starting Nmap 7.95 ( https://nmap.org ) at 2024-06-13 01:53 BST
Unexpected error in NSE_TYPE_READ callback.  Error code: 50 (Network is down)
QUITTING!`

The same `Error code: 50` output results when using the `Quick scan plus` profile in the Zenmap GUI.

**Comment by EricZheng0404** [comment]
> [@fyodor](https://github.com/fyodor) seems like it was fixed in 7.95

I'm using M2 Macbook on macOS 14.6.1 with Nmap 7.95, still having this issue.

**Comment by A-Waters** [comment]
was running into this issue on `macOS 15.5 arm64`
```
nmap X -vv -A
...
Completed Connect Scan at 11:54, 62.70s elapsed (1000 total ports)
Initiating Service scan at 11:54
Scanning 3 services on X
Unexpected error in NSE_TYPE_READ callback.  Error code: 50 (Network is down)
QUITTING!
```

but pulling the most recent nmap seemed to resolve it 
`brew upgrade nmap`
