### ISSUE TITLE
Npcap: No "Monitor Mode" checkbox in “Capture options” in Wireshark

### ISSUE THREAD

**Issue by taismi** [nmap/nmap#757]
There is no No "Monitor Mode" checkbox in “Capture options” in Wireshark (GTK version) 2.2.5. No packets are captured. I'm using Netgear A6200 with newest drivers. Windows 10 64 bit.

I have tried to follow Wireshark section in https://rawgit.com/nmap/npcap/master/docs/npcap-guide-wrapper.html#npcap-feature-dot11 .

```
C:\Program Files\Npcap>NPFInstall.exe -i2
Npcap LWF driver (with Wi-Fi support) has been successfully installed!
```

Diag report: http://pastebin.com/3urTeM6x

Instal log: http://pastebin.com/LkcqK94e

http://i.imgur.com/WS7mqnp.png

This might be a simple problem but I can't capture packets and I'm in hurry.

**Comment by hsluoyz** [comment]
Hi @taismi,

Your DiagReport and Install log have expired:

![image](https://cloud.githubusercontent.com/assets/3787410/26516530/3e8ea9b2-42ba-11e7-8537-628d4e4abdee.png)

Could you upload it in this conversation? Thanks.

**Comment by hsluoyz** [comment]
Hi @taismi ,

I just tested it under Npcap 0.90, Wireshark 2.2.6 QT, Windows 10 x64. And the monitor mode works well like the following picture:

![image](https://cloud.githubusercontent.com/assets/3787410/26517927/39ac8060-42d6-11e7-84ba-e6d4893dbf22.png)

Please do not install the wifi driver by calling ``NPFInstall.exe -i2`` manually. That command may not work any more. Please use the Npcap GUI installer, and choose the 802.11 option. It's the safest way.

And you can use the Wireshark QT GUI, instead of the GTK one. I found that the GTK UI doesn't have a place to set the monitor mode in 2.2.6. Maybe Wireshark has disabled this feature in this release. So please try it with the QT UI.

**Comment by taismi** [comment]
![wireshark-gui-monitor_mode](https://cloud.githubusercontent.com/assets/16210105/26540379/e8583ef4-4459-11e7-8ebd-36cff2df0883.png)

Install log: https://pastebin.com/BzDi7D51
Diag: https://pastebin.com/w70hUGiL

**Comment by hsluoyz** [comment]
Let me store it here in case it's gone again..

[DiagReport.txt](https://github.com/nmap/nmap/files/1035191/DiagReport.txt)

[Install.txt](https://github.com/nmap/nmap/files/1035196/Install.txt)

**Comment by hsluoyz** [comment]
From your DiagReport, I saw:

```
    Directory: C:\WINDOWS\System32
 
 
Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----         1.3.2013      3.49         107768 Packet.dll                                                            
-a----         1.3.2013      3.49         370424 wpcap.dll  
```

It means that you didn't uninstall WinPcap 4.1.3 thoroughly last time. And its DLLs (wpcap.dll, Packet.dll) still remain in ``C:\WINDOWS\System32`` (and also ``C:\WINDOWS\SysWOW64`` for 32-bit apps). So please remove those WinPcap legacy DLLs manually at those folders. And try again.

**Comment by taismi** [comment]
Thanks. Now there is monitor mode checkbox and I can see beacon frames etc.

For sure I reinstalled Netgear A6200 drivers and Npcap. Interface name WLAN2 is now Microsoft: WLAN.
I installed A6200-standalone-V1.0.0.35.exe. Wireless toolbar in Wireshark i grayed out so I can't change channel. I cannot find channel information from radiotap header either.

**Comment by hsluoyz** [comment]
If I remember right, Netgear A6200 just doesn't support changing channel on Windows. I don't know this is limited by its hardware or by its driver on Windows. If it can work on another OS like Ubuntu, then it should be the driver issue. It is hardly Npcap's problem, because I have implemented the changing channel code in Npcap driver, and Npcap can change channel in another adapter of mine (an Atheros NIC on my last laptop).

You can make a little more test to re-check this thing. Use the ``WlanHelper.exe`` utility installed with Npcap, should be in ``C:\WINDOWS\System32\Npcap``. It supports doing the Wlan specific operations, have better functionality than the Wireshark UI. Use ``-h`` to see the help.

**Comment by taismi** [comment]
This worked.
WlanHelper 8c309594-364d-425a-98f7-7ba157b84aa6 channel 11

My Netgear A6200 has a Broadcom BCM43526 chip. Netgear A6210 has a MediaTek MT7612U chip. If I have time I'll test A6210 tomorrow.

Many thanks to you. Finally I can start debugging our wlan promlems.

**Comment by hsluoyz** [comment]
OK. I'll close the issue now.

**Comment by huzaifazafar108** [comment]
@taismi do you think the A7000 supports network monitor mode?

I used the same steps as mentioned in this thread but still unable to see the monitor mode checkbox in Wireshark. Kindly help when you get a chance.

**Comment by hsluoyz** [comment]
Please paste the error of WlanHelper.exe here.

**Comment by rafafilho11** [comment]
My wireshar is on the promiscouous mode, but I can't see the WLAN traffic information when I see on the wireshark. Can anyone help me ?

SSID:	MySSID
Protocolo:	802.11n
Tipo de segurança:	WPA2-Personal
Banda de rede:	2,4 GHz
Canal de rede:	11
Fabricante:	Intel Corporation
Descrição:	Intel(R) Dual Band Wireless-N 7260
Versão do driver:	18.33.7.2

![image](https://user-images.githubusercontent.com/42524715/44314583-4b441900-a3f1-11e8-961b-eb82a330a5c5.png)

![image](https://user-images.githubusercontent.com/42524715/44314600-79c1f400-a3f1-11e8-8419-7db42ac0e3b1.png)
